[[manager.prepend_keymap]]
on = [ "!" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on  = "<C-n>"
run = '''
    shell 'ripdrag "$@" -xn 2>/dev/null &' --confirm
'''

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"
